PREFIX 	rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX 	xml: <http://www.w3.org/XML/1998/namespace>
PREFIX 	wf: <http://geographicknowledge.de/vocab/Workflow.rdf#>
PREFIX  gis: <http://geographicknowledge.de/vocab/GISConcepts.rdf#>
PREFIX  ada: <http://geographicknowledge.de/vocab/AnalysisData.rdf#>
PREFIX  owl: <http://www.w3.org/2002/07/owl#>
PREFIX 	maup: <http://geographicknowledge.de/vocab/MAUP.rdf#>

CONSTRUCT { ?d a maup:UniformSSize}
WHERE {
?d a ada:DataSet . 
FILTER NOT EXISTS{ 
?d ada:hasElement ?e1 . ?e1 ada:hasSupport ?s1 . ?s1  gis:hasSize ?q1 .
?d ada:hasElement ?e2 . ?e2 ada:hasSupport ?s2 . ?s2  gis:hasSize ?q2 .
FILTER(?q1 != ?q2)
}
}