
PREFIX ada: <http://geographicknowledge.de/vocab/AnalysisData.rdf#>
PREFIX gis: <http://geographicknowledge.de/vocab/GISConcepts.rdf#>
PREFIX wf: <http://geographicknowledge.de/vocab/Workflow.rdf#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX m: <http://www.w3.org/TR/MathML/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema>

CONSTRUCT { ?method wf:output ?target_layer_in . ?method  wf:input ?layer_in. }
WHERE {
   ?layer_in a ada:DataSet.
   ?target_layer_in a ada:DataSet. 
   FILTER NOT EXISTS {
     ?target_layer_in ada:hasElement ?target_element.
     ?target_element ada:hasMeasure ?target_measure.
     FILTER NOT EXISTS {
     ?innermethod wf:input ?layer_in .  
	 ?innermethod wf:output ?target_measure .  ?innermethod a gis:Interpolate.    
	}}}