PREFIX ada: <http://geographicknowledge.de/vocab/AnalysisData.rdf#>
PREFIX gis: <http://geographicknowledge.de/vocab/GISConcepts.rdf#>
PREFIX wf: <http://geographicknowledge.de/vocab/Workflow.rdf#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX m: <http://www.w3.org/TR/MathML/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema>

CONSTRUCT {
?rr wf:fstInput ?l_in. ?rr gis:param ?intpl. 
?rr wf:output ?l_out. ?rr a gis:RasterResampling. }
WHERE { 
 ?l_in a gis:Raster. 
 ?l_out a gis:Raster. 
 ?intpl a gis:Interpolate .
 FILTER NOT EXISTS{
   ?eo ada:elementOf ?l_out .    
	?eo ada:hasMeasure ?attribute.   
   FILTER NOT EXISTS{   		
       ?intpl wf:fstInput ?l_in .  ?intpl wf:sndInput ?eo .
       ?intpl wf:output ?attribute.    		
   }
 }
}